<<<<<<< HEAD
src_dir: ./libraries/
coverage_clover: build/logs/clover.xml
json_path: build/logs/coveralls-upload.json
=======
src_dir: ./libraries/
coverage_clover: build/logs/clover.xml
json_path: build/logs/coveralls-upload.json
>>>>>>> b875702c9c06ab5012e52ff4337439b03918f453
